CREATE SEQUENCE USER_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE;

CREATE OR REPLACE TYPE ADDRESS_TYPE AS
    OBJECT (
        STREET VARCHAR2(100),
        REGION VARCHAR2(50),
        DISTRICT VARCHAR2(50),
        COUNTRY VARCHAR2(50)
    );
/

CREATE TABLE USERS (
    USERID NUMBER DEFAULT USER_ID_SEQ.NEXTVAL NOT NULL,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    FULLNAME VARCHAR2(255) GENERATED ALWAYS AS (FIRSTNAME
                                                || ' '
                                                || LASTNAME),
    EMAIL VARCHAR(255) NOT NULL,
    DATE_OF_BIRTH DATE,
    BLOOD_GROUP VARCHAR(5),
    PHONE_NUMBER VARCHAR(16),
    ADDRESS ADDRESS_TYPE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_USERID PRIMARY KEY (USERID)
);

ALTER TABLE USERS
    ADD CONSTRAINT CHK_PHONE CHECK (
        LENGTH(PHONE_NUMBER) BETWEEN 11 AND 16
    );

ALTER TABLE USERS
    ADD AGE NUMBER;

CREATE OR REPLACE PROCEDURE UPDATEUSERAGES IS
BEGIN
    UPDATE USERS
    SET
        AGE = FLOOR(
            MONTHS_BETWEEN(SYSDATE, DATE_OF_BIRTH) / 12
        )
    WHERE
        DATE_OF_BIRTH IS NOT NULL;
    COMMIT;
END UPDATEUSERAGES;
/

CREATE TABLE DOCTORS (
    BMDC VARCHAR(100) NOT NULL,
    FULLNAME VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL,
    GENDER VARCHAR2(10),
    PHONE VARCHAR2(15),
    DEPT VARCHAR2(100),
    MBBSYEAR NUMBER NOT NULL,
    HOSP VARCHAR2(255),
    CHAMBER VARCHAR2(255),
    EXPERIENCE NUMBER,
    TOTAL_OPERATIONS NUMBER,
    DATE_OF_BIRTH DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_BMDC PRIMARY KEY (BMDC)
);

CREATE TABLE PASSWORDS (
    USERID NUMBER,
    HASHED_PASSWORD VARCHAR(255),
    BMDC VARCHAR(100),
    CONSTRAINT FK_USERID FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE,
    CONSTRAINT FK_BMDC FOREIGN KEY (BMDC) REFERENCES DOCTORS(BMDC) ON DELETE CASCADE
);

CREATE TABLE USER_IMAGES (
    IMAGE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    FILENAME VARCHAR2(255) NOT NULL,
    MIME_TYPE VARCHAR2(100) NOT NULL,
    IMAGE_DATA BLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USERID)
);

CREATE TABLE DOCTOR_IMAGES (
    IMAGE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BMDC VARCHAR(255) NOT NULL,
    FILENAME VARCHAR2(255) NOT NULL,
    MIME_TYPE VARCHAR2(100) NOT NULL,
    IMAGE_DATA BLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK__IMAGE_BMDC FOREIGN KEY (BMDC) REFERENCES DOCTORS(BMDC)
);